# Site settings
title_left      : "Nicole Li"
title_right     : "" # default: ""
description     : ""
keywords        : ""
url             : https://nicole-li.github.io/ # site url
baseurl         : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover           : assets/images/apple-touch-icon.png # image uri like logo/cover image for site seo
logo            : assets/images/android-chrome-192x192.png

google_analytics  : UA-XXXXX-XX
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Nicole Li"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : projects
    title: Projects
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
